Telecominfraproject/wlan-cloud-ui-library

package.json
src/components/Loading/index.js
src/components/Loading/index.module.scss
src/components/NetworkTable/index.js
src/components/NetworkTable/index.module.scss
src/components/ToggleButton/index.js
src/containers/Network/index.js
src/containers/Network/index.module.scss
src/index.js

JIRA: [TW-465](https://connectustechnologies.atlassian.net/browse/TW-183)
Refactored the Network page to have child pages as nested routes

Feature/tw-465: Network Page

---

package.json
src/containers/AccessPointDetails/components/Location/index.js
src/containers/ProfileDetails/components/Radius/components/ManagementSubnet/index.js
src/containers/ProfileDetails/components/Radius/components/RadiusServer/index.js
src/containers/ProfileDetails/components/Radius/components/RadiusService/index.js
src/containers/ProfileDetails/components/Radius/components/RadiusZone/index.js
src/containers/ProfileDetails/components/Radius/index.js
src/containers/ProfileDetails/components/index.module.scss
src/containers/ProfileDetails/index.js
src/utils/profiles.js

JIRA: [TW-196](https://connectustechnologies.atlassian.net/browse/TW-196)

feature/TW-196: RADIUS profiles

---

src/containers/Dashboard/components/PieChart/index.js

Feature/dashboard piechart: rename

---

package-lock.json
src/containers/ProfileDetails/components/CaptivePortal/index.js
src/containers/ProfileDetails/components/Radius/components/RadiusService/index.js
src/containers/ProfileDetails/components/Radius/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/components/index.module.scss
src/containers/ProfileDetails/index.js
src/utils/profiles.js

JIRA: [TW-606](https://connectustechnologies.atlassian.net/browse/TW-606)
finished Captive Portal Profile

Feature/tw-606: Captive Portal Profile

---

src/containers/AccessPointDetails/components/Firmware/index.js
src/containers/AccessPointDetails/components/Firmware/tests/index.test.js
src/containers/AccessPointDetails/index.js
src/containers/AccessPointDetails/index.module.scss

JIRA: [TW-472](https://connectustechnologies.atlassian.net/browse/TW-472)
*Updated Firmware Tab*
*
*

Feature:TW-472: Updated Firmware Tab

---

src/components/LocationsTree/components/AddApModal/index.js
src/components/LocationsTree/components/PopoverMenu/index.js
src/components/LocationsTree/components/PopoverMenuContent/index.js
src/components/LocationsTree/components/PopoverMenuContent/tests/index.test.js
src/components/LocationsTree/index.js
src/components/LocationsTree/tests/index.test.js
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/index.js
src/containers/Network/index.js

JIRA: [W-724](https://connectustechnologies.atlassian.net/browse/TW-724)
*Bind an Access Point to a customer based on the location*
*
*

feature/TW-724: Add Access Point

---

src/components/Navbar/index.js
src/components/Navbar/index.module.scss
src/containers/AccessPointDetails/components/OS/components/SolidGauge/index.js
src/containers/AccessPointDetails/components/OS/components/SolidGauge/index.module.scss
src/containers/AccessPointDetails/components/OS/index.js
src/containers/AppLayout/index.js
src/containers/Dashboard/components/DeviceStatsCard/index.js
src/containers/Dashboard/components/PieChart/index.js
src/containers/Dashboard/components/PieChart/index.module.scss
src/containers/Dashboard/index.module.scss

JIRA: [TW-841](https://connectustechnologies.atlassian.net/browse/TW-841)
*combine Client 5Ghz counts, OS stats temperature change unit to C, Alarms count change to Navbar, fixed Dashboard UI*
*
*

Feature/TW-841 - Marcel's Revised Changes

---

package.json
src/containers/AutoProvision/components/FormModal/index.js
src/containers/AutoProvision/index.js
src/containers/AutoProvision/index.module.scss
src/containers/AutoProvision/tests/index.test.js
src/containers/Firmware/components/VersionModal/index.js
src/containers/ProfileDetails/components/CaptivePortal/index.js
src/containers/ProfileDetails/components/CaptivePortal/tests/index.test.js
src/containers/System/index.js
src/index.js

JIRA: [TW: 929](https://connectustechnologies.atlassian.net/browse/TW-929)
*

Feature/TW: 929 - Auto Provision Page

---

src/components/LocationsTree/components/AddApModal/tests/index.test.js
src/components/LocationsTree/components/EditFormModal/tests/index.test.js
src/components/LocationsTree/components/PopoverMenuContent/tests/index.test.js
src/components/LocationsTree/tests/index.test.js

*Added unit tests for LocationTree component*

UnitTest: Updated unit tests for locationTree component

---

src/components/LocationsTree/components/PopoverMenuContent/index.js
src/components/LocationsTree/index.js
src/components/LocationsTree/index.module.scss
src/containers/Network/index.js

JIRA: [TW-917](https://connectustechnologies.atlassian.net/browse/TW-917)
*Added location button to top of TreeView to create root location*

Feature/TW-917: Add Location Button to top of TreeView to create root location

---

src/containers/Alarms/tests/index.test.js

JIRA: [TW-984](https://connectustechnologies.atlassian.net/browse/TW-984)
*Added unit tests*

Feature/TW-984: Added unit tests for alarms component

---

src/containers/Dashboard/components/DeviceStatsCard/test/index.test.js
src/containers/Dashboard/components/LineChart/test/index.test.js
src/containers/Dashboard/components/PieChart/test/index.test.js
src/containers/Dashboard/test/index.test.js

JIRA: [TW-985](https://connectustechnologies.atlassian.net/browse/TW-985)
*Added unit tests*

Feature/TW-985: added unit tests for dashboard components

---

src/containers/Profile/index.js

Added Equipment Count values for Profiles table
*
*
*

hotfix/WIFI-584: Added Equipment Count

---

src/containers/ProfileDetails/components/Radius/components/ManagementSubnet/index.js
src/containers/ProfileDetails/components/Radius/tests/index.test.js

Fixed broken Radius test and fixed bug which would allow user to enter a Subnet CIDR Mask below 0*
*Screenshots of what it looked like before this PR 
*
*

hotfix/Radius - fixed test and bug

---

src/components/Loading/index.js
src/containers/AccessPointDetails/components/Firmware/index.js
src/containers/AccessPointDetails/components/Firmware/tests/index.test.js
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/General/tests/index.test.js
src/containers/AccessPointDetails/index.js
src/containers/AccessPointDetails/tests/constants.js

*Summary of this PR 
Split up Alerts and Loading for profiles and firmware*
*

hotfix/WIFI-571: updated firmware query

---

package-lock.json
package.json
src/containers/AddProfile/index.js
src/containers/Profile/index.js
src/containers/Profile/index.module.scss
src/containers/Profile/tests/index.test.js
src/containers/ProfileDetails/components/BonjourGateway/index.js
src/containers/ProfileDetails/components/BonjourGateway/tests/index.test.js
src/containers/ProfileDetails/components/index.module.scss
src/containers/ProfileDetails/index.js
src/containers/ProfileDetails/tests/index.test.js
src/utils/profiles.js

JIRA: [TW-977](https://connectustechnologies.atlassian.net/browse/TW-977)
Bonjour Gateway Form*
*

Feature/TW-977: Bonjour Gateway 

---

src/containers/Profile/index.js
src/containers/Profile/tests/index.test.js

JIRA: [WIFI-590](https://telecominfraproject.atlassian.net/browse/WIFI-590)
Fix modal name for deleting a profile
Self explanantory
Self explanantory

hotfix/WIFI-590: Delete profile modal text

---

src/containers/Profile/index.js
src/containers/Profile/index.module.scss

Previously, just the labels on the Profile table was clickable. Now the entire row is clickable, and routes to the specific profile.*

hotfix/WIFI-591 - Entire row on profiles table is clickable

---

src/components/Tooltip/index.js
src/components/Tooltip/index.module.scss
src/containers/AccessPointDetails/index.module.scss
src/containers/AddProfile/index.js
src/containers/AddProfile/index.module.scss
src/containers/AutoProvision/index.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/CaptivePortal/index.js
src/containers/ProfileDetails/components/CaptivePortal/tests/index.test.js
src/containers/ProfileDetails/components/Radius/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/components/index.module.scss
src/containers/ProfileDetails/index.js
src/styles/index.scss

Removed Double border on some input fields, changed config of tooltips on Profile forms to use custom tooltip instead of Antd one, changed label span on forms to be consistent side wide*
*Screenshots of what it looked like before this PR 
*

hotfix/WIFI-589: Removed Double Border

---

src/containers/AccessPointDetails/tests/index.test.js

fixed broken tests on AP details page*

hotfix/APDetails - fixed tests

---

src/containers/ProfileDetails/components/Radius/index.js

Removed prop bsSize on Radius page that was causing error *

hotfix/Radius: removed broken prop on radius page

---

src/containers/ProfileDetails/components/Radius/components/RadiusService/index.js

JIRA: [WIFI-772](https://telecominfraproject.atlassian.net/browse/WIFI-772)
Change setIps() to use filter function instead of splice function to delete the selected row. Found in the Edit RADIUS Service modal

hotfix/WIFI-772: Fixed delete button to delete selected row

---

src/containers/ProfileDetails/components/Radius/components/ManagementSubnet/index.js

JIRA: [WIFI-779](https://telecominfraproject.atlassian.net/browse/WIFI-779)
The subnet CIDR mask input now accepts a subnet mask input by converting it into CIDR value and saving the value as the input. 
Still accepts normal CIDR value with no conversion needed.

hotfix/WIFI-779: Fixed Subnet CIDR mask input to accept both CIDR and Subnet mask input

---

src/containers/Login/index.js

JIRA: [WIFI-787](https://telecominfraproject.atlassian.net/browse/WIFI-787)
- Login email input accepts upper and lower case emails via handleSubmit converts to lower case

hotfix/WIFI-787: fixed login to accept uppercase emails

---

src/index.js

JIRA: NOJIRA
Add modal as an export.
n/a
n/a

Add Modal export

---

src/containers/ProfileDetails/components/CaptivePortal/index.js

JIRA: [WIFI-819](https://telecominfraproject.atlassian.net/browse/WIFI-819)
- Fixed validation of sessionTimeOutInMinutes lower bound range validation to exclude negative and 0 values

hotfix/WIFI-819: fixed sessionTimeOutInMinutes lower bound validation range

---

src/utils/profiles.js

JIRA: [WIFI-949](https://telecominfraproject.atlassian.net/browse/WIFI-949)
- edit save of radius profile failed due to probe interval not being read-only
- solution is to deep close the properties taken from the backend which are read-only

hotfix/WIFI-949: fixed radius profile edit-save issue

---

src/containers/Profile/index.js

JIRA: [WIFI-804](https://telecominfraproject.atlassian.net/browse/WIFI-804)
- added option to delete captive portal profiles on the Profiles table

hotfix/WIFI-804: Added captive_portal delete button option in Profiles Table

---

src/containers/AddProfile/index.js

JIRA: [WIFI-803](https://telecominfraproject.atlassian.net/browse/WIFI-803)
- added an option for Captive Portal in the /addprofile page
- when selected Captive Portal form appears underneath and can be saved

hotfix/WIFI-803: Added option to create Captive Portals

---

src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
src/containers/Dashboard/components/LineChart/index.js

JIRA: [WIFI-1017](https://telecominfraproject.atlassian.net/jira/software/c/projects/WIFI/issues/WIFI-1017?jql=project%20%3D%20%22WIFI%22%20AND%20assignee%20IN%20%28currentUser%28%29%29%20ORDER%20BY%20created%20DESC)
Fixed the plotting graph to display plotting stats in AP Details OS Stats page

hotfix/WIFI-1017: Displayed plotting stats in AP Details OS Stats page

---

src/index.js

- Added Header and Container Exports for these components to be used in cmap-ui

Added Header and Container Exports

---

src/components/LocaleItem/index.js
src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/Venue/components/FormModal/index.js
src/containers/ProfileDetails/components/Venue/components/FormModal/tests/index.test.js
src/containers/ProfileDetails/components/Venue/index.js
src/containers/ProfileDetails/components/Venue/tests/index.test.js
src/containers/ProfileDetails/index.js

JIRA: [WIFI-1086](https://telecominfraproject.atlassian.net/browse/WIFI-1086)
- Added Passpoint Venue Profile Form

feature/WIFI-1086 Adding a Venue Profile

---

src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
src/containers/ProfileDetails/components/Radius/tests/index.test.js
src/containers/ProfileDetails/tests/index.test.js

JIRA: [NETEXP-584](https://connectustechnologies.atlassian.net/browse/NETEXP-584)
- default of `ntp` is uncheck and state should be set to false. 
- Before `ntp` default was true even when unchecked. when returning to AP profile,  `ntp` was to set incorrectly

hotfix/NETEXP-584: fixed default state of ntpServer

---

src/containers/ProfileDetails/components/Operator/index.js
src/containers/ProfileDetails/components/PasspointProfile/index.js
src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js
src/containers/ProfileDetails/components/ProviderId/index.js
src/containers/ProfileDetails/index.js
src/utils/profiles.js

Added ssid field and hides file upload based on authentication type

hotfix/Passpoint- Bug fixes

---

src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/Status/index.js
src/containers/ClientDeviceDetails/index.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/PasspointProfile/index.js
src/containers/ProfileDetails/components/RF/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/contexts/ThemeProvider/index.js

JIRA: [NETEXP-750](https://connectustechnologies.atlassian.net/secure/RapidBoard.jspa?rapidView=11&modal=detail&selectedIssue=NETEXP-750&assignee=5f91b571f162650070d4dc94)
Added user friendly radio types across the app

hotfix/NETEXP-750: Friendly Radio Names

---

package-lock.json
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/OS/tests/index.test.js
src/containers/AccessPointDetails/index.js

JIRA: [NETEXP-783](https://connectustechnologies.atlassian.net/browse/NETEXP-783)
- changed fields of AP Details and General tab to new `baseMacAddress` and `manufacturer` fields

bugfix/NETEXP-783: AP details to use baseMacAddress and manufacturer

---

src/components/NetworkTable/index.js

NOJIRA
CD table row click should use MAC address not id 

hotfix/NOJIRA: Go to mac address not id

---

src/components/NetworkTable/index.js
src/containers/NetworkTableContainer/index.js

NOJIRA
Add active tab to network table so it knows which route to go to

hotfix: Network table routing changes depending on active tab

---

src/containers/AddProfile/index.js
src/containers/Manufacturer/index.js
src/containers/ProfileDetails/components/Operator/index.js
src/utils/profiles.js

JIRA: [NETEXP-557](https://connectustechnologies.atlassian.net/secure/RapidBoard.jspa?rapidView=11&modal=detail&selectedIssue=NETEXP-557&assignee=5f91b571f162650070d4dc94)
input form validation

hotfix/NETEXP-557: Input validations

---

src/containers/ClientDeviceDetails/index.js
src/containers/ClientDeviceDetails/tests/index.test.js

NOJIRA, needed for inventory page
Make back button on cd details use history native back

Make back button on cd details use native back

---

src/containers/Accounts/components/FormModal/index.js
src/containers/Accounts/index.js

JIRA: [NETEXP-807](https://connectustechnologies.atlassian.net/secure/RapidBoard.jspa?rapidView=11&modal=detail&selectedIssue=NETEXP-807&assignee=5f91b571f162650070d4dc94)
Added password reset buttons

feature/NETEXP-807: Reset password buttons

---

src/containers/AccessPointDetails/components/General/index.js

NETEXP-563
Bugfix to view SKU and country code

bugfix/NETEXP-563: SKU and Country Code

---

src/containers/AccessPointDetails/components/General/index.js

NETEXP-856
Separate RF profile from rest

bugfix/NETEXP-856: RF Profile misplaced

---

src/components/Navbar/index.js
src/components/Navbar/index.module.scss
src/components/SettingsDropdown/index.js
src/containers/AppLayout/index.js

JIRA: [NETEXP-795](https://connectustechnologies.atlassian.net/browse/NETEXP-795)
Update 2021-01-05
- Added option to change rightMenuItem
- adjusted css

bugfix/NETEX-795: Added prop to change rightMenuItem

---

src/containers/Accounts/tests/index.test.js
src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
src/containers/ProfileDetails/index.js
src/containers/ProfileDetails/index.module.scss
src/containers/ProfileDetails/tests/index.test.js

JIRA: [NETEXP-523](https://connectustechnologies.atlassian.net/browse/NETEXP-523)
- Added prop for extra buttons to `ProfileDetails` page's Header
- Added prop `initialValues` to `Addprofile` page
- included fixes to make add profile more consistent with profile details for `SSID`, `Captive Portal`, and `Passpoint`

Bugfix/NETEXP-523: Added extraButtons prop to ProfileDetails and modified AddProfile

---

src/containers/ProfileDetails/components/AccessPoint/index.js

JIRA: [N/A](LINK)
- Added default value to ntp state

Added default value to ntp state

---

src/containers/AddProfile/index.js
src/containers/AddProfile/index.module.scss
src/containers/Profile/index.js
src/containers/ProfileDetails/index.js
src/containers/ProfileDetails/index.module.scss

JIRA: [N/A](LINK)
- changed title and location of `Add Profile` Page & `Profile Details` Page
- changed Button name on `Add Profile` Page
- changed button name on `Profile` Page

Changed title location and button name on Add Profile Page

---

src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/RF/index.js
src/containers/ProfileDetails/components/SSID/index.js

JIRA: [NETEXP-855](https://connectustechnologies.atlassian.net/browse/NETEXP-855)
Address UX feedback comments and 
Add keys to prevent console errors

NETEXP-855: UX Feedback

---

package-lock.json
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/General/tests/index.test.js
src/containers/AccessPointDetails/index.js

JIRA: [NETEXP-974](https://connectustechnologies.atlassian.net/browse/NETEXP-974)
Select dropdown for Access Point Profile is searchable and contains auto complete functionality. Supports paginated data. 

feature/NETEXP-974: Search functionality to AP profile select

---

package-lock.json
package.json
src/components/Button/index.module.scss
src/components/ToggleButton/index.module.scss
src/containers/AccessPointDetails/components/Firmware/tests/index.test.js
src/containers/AccessPointDetails/tests/constants.js
src/containers/AccessPointDetails/tests/index.test.js
src/containers/AddProfile/index.js
src/containers/Profile/tests/index.test.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
src/containers/ProfileDetails/components/CaptivePortal/index.js
src/containers/ProfileDetails/components/PasspointProfile/index.js
src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/constants/index.js
src/containers/ProfileDetails/index.js
src/styles/index.scss

JIRA: [NETEXP-989](https://connectustechnologies.atlassian.net/browse/NETEXP-989)
Fixed:
-While creating a new AP profile under the SSID profile section, search function does not work always
-Scrolling to the bottom of the select would sometimes not fetch additional profile data
Added:
-Search functionality for all profile selects to make them consist with the SSID select

bugfix/NETEXP-989: Fixed Select Dropdowns on Add/Edit Account pages 

---

package-lock.json
src/containers/AccessPointDetails/index.js
src/containers/AccessPointDetails/index.module.scss
src/containers/ClientDeviceDetails/index.js
src/containers/ClientDeviceDetails/index.module.scss

JIRA: [NETEXP-913](https://connectustechnologies.atlassian.net/browse/NETEXP-913)
Quick Link on all the Network pages (Overview, Inventory, Details) for equipment and devices to go to the Metrics / Logs pages for that specific item. 
-Quick Link for Client Device Logs not done. 

feature/NETEXP-913: Quick Link from Network to Troubleshoot page

---

src/containers/ProfileDetails/components/Radius/index.js
src/containers/ProfileDetails/components/Radius/tests/index.test.js

JIRA: [WIFI-1441](https://telecominfraproject.atlassian.net/browse/WIFI-1441)
Removed timeout input for RADIUS page. 

bugfix/WIFI-1441: Deleted RADIUS server timeout input

---

src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/components/SSID/tests/index.test.js
src/containers/ProfileDetails/components/constants.js

JIRA: [WIFI-1440](https://telecominfraproject.atlassian.net/browse/WIFI-1440)
Added radiusAcountingServiceInterval field in the SSID page. 

bugfix/WIFI-1440 : radiusAcountingServiceInterval field for ssid page

---

src/containers/ProfileDetails/index.js
src/containers/ProfileDetails/tests/index.test.js

JIRA: [WIFI-1513](https://telecominfraproject.atlassian.net/browse/WIFI-1513)
Save button is disabled when no changes to the page are made. 

bugfix/WIFI-1513: Save button disabled when form is unchaged

---

src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/General/tests/index.test.js
src/containers/ProfileDetails/components/RF/index.js
src/containers/ProfileDetails/components/RF/tests/index.test.js

JIRA: [WIFI-1501](https://telecominfraproject.atlassian.net/browse/WIFI-1501)
Fixed Input range for EIRP Tx Power.

bugfix/WIFI-1501: fixed input range for EIRP Tx Power

---

src/containers/ProfileDetails/components/SSID/index.js

JIRA: [WIFI-1492](https://telecominfraproject.atlassian.net/browse/WIFI-1492)
Changed roaming options panel on SSID page:
- 802.11r field to be available for the current setup of security modes and the 802.11k and 802.11v to be available for all

bugfix/WIFI-1492: fixed security mode conditions

---

src/components/LocationsTree/components/AddApModal/index.js
src/components/LocationsTree/components/AddFormModal/index.js
src/components/LocationsTree/components/EditFormModal/index.js
src/containers/AccessPointDetails/components/Firmware/index.js
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/Location/index.js
src/containers/Accounts/components/FormModal/index.js
src/containers/AddProfile/index.js
src/containers/AutoProvision/components/FormModal/index.js
src/containers/BlockedList/components/FormModal/index.js
src/containers/EditAccount/index.js
src/containers/Firmware/components/AssignmentModal/index.js
src/containers/Firmware/components/VersionModal/index.js
src/containers/Login/index.js
src/containers/ProfileDetails/components/AccessPoint/components/FormModal/index.js
src/containers/ProfileDetails/components/CaptivePortal/components/FormModal/index.js
src/containers/ProfileDetails/components/PasspointProfile/components/FormModal/index.js
src/containers/ProfileDetails/components/ProviderId/components/FormModal/index.js
src/containers/ProfileDetails/components/ProviderId/index.js
src/containers/ProfileDetails/components/Venue/components/FormModal/index.js
src/containers/ProfileDetails/index.js
src/utils/form.js

JIRA: ID
Description
Summary of this PR
Made layout for forms consistent:
- Modal forms layouts are `labelCol: { span: 8 }` , and `wrapperCol: { span: 12 }`
- Regular page layouts are `labelCol: { span: 5 }` , and `wrapperCol: { span: 15 }`
Before this PR
Screenshots of what it looked like before this PR
After this PR
Screenshots of what it will look like after this PR

hotfix/FormLayouts: Fixed layout for forms

---

src/containers/Firmware/components/VersionModal/index.js
src/containers/Firmware/components/VersionModal/tests/index.test.js
src/containers/Firmware/tests/index.test.js

JIRA: [WIFI-1607](https://telecominfraproject.atlassian.net/browse/WIFI-1607)
Remove Validation Code (MD5) input from Add Firmware Modal

hotfix/WIFI-1607: Removed Validation Code (MD5) input from Add Firmware Modal

---

src/containers/AccessPointDetails/index.js
src/containers/AccessPointDetails/index.module.scss

Added Support for Extra Tabs on AP Details page

feature/NETEXP-1178: Added Support for Extra Tabs on AP Details Page

---

src/containers/AddProfile/index.js

JIRA: [WIFI-1486](https://telecominfraproject.atlassian.net/browse/WIFI-1486)
Added extraFields prop for for the RX Cell Size field on the RF-Profile. 

hotfix/AddProfileProps: Added extraFields prop 

---

src/containers/ProfileDetails/components/RF/index.js

JIRA: [WIFI-1464)](https://telecominfraproject.atlassian.net/browse/WIFI-1464)
Changed radioMode enum for AX mode from `modeX` to `modeAX` for RF Profile

hotfix/WIFI-1464: Changed radioMode enum for RF Profile

---

src/containers/AutoProvision/index.js
src/containers/AutoProvision/tests/index.test.js

Bug in the saving function for the Auto-Provision Page that prevented the formatted data object to be modified before being saved. 

hotfix/AutoProvisionPage: Fixed saving bug

---

src/containers/ProfileDetails/components/AccessPoint/components/FormModal/index.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/CaptivePortal/index.js
src/containers/ProfileDetails/index.js

JIRA: [WIFI-1613](https://telecominfraproject.atlassian.net/browse/WIFI-1613)
- Fixed bug where save button would remain disabled even though there were changes done to AP and CP page
- Fixed bug on Add GRE modal for AP page that prevented adding values where the VLAN Ids field was null

hotfix/WIFI-1613: Save button disabled bug

---

src/containers/AccessPointDetails/components/Firmware/index.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/constants/index.js
src/utils/profiles.js

JIRA: [WIFI-1488](https://telecominfraproject.atlassian.net/browse/WIFI-1488)
> Added default ntp server value as "pool.ntp.org" when the "Use Default Servers" checkbox is checked
> Used the correct prop `wrapperCol` for certain form fields

bugfix/WIFI-1488: Default NTP Server Value

---

src/components/Navbar/index.js
src/components/SettingsDropdown/index.js
src/containers/AppLayout/index.js

JIRA: [WIFI-1452](https://telecominfraproject.atlassian.net/browse/WIFI-1452)
Fixed bug on Edit User page that prevents access of the Edit User page when the user id is 0. 

bugfix/WIFI-1452: Fixed bug on Edit User Page

---

src/containers/AccessPointDetails/components/Location/index.js

JIRA: [NETEXP-1228](https://connectustechnologies.atlassian.net/browse/NETEXP-1228)
- Fixed bug on AP Details page that would delete details property on update.
- Fixed bug that would prevent saving of location when the last location floor did not have any children. 

bugfix/NETEXP-1228: Access Point location update bug

---

src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
src/containers/AccessPointDetails/components/OS/components/SolidGauge/index.js
src/containers/Dashboard/components/LineChart/index.js
src/containers/Dashboard/components/PieChart/index.js

JIRA: [NETEXP-1229](https://connectustechnologies.atlassian.net/browse/NETEXP-1229)
Fixed axis labels for Highcharts graphs to make them more readable.

bugfix/NETEXP-1229: Fixed highcharts label colors

---

src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/Status/index.js
src/containers/AccessPointDetails/index.js

JIRA: [NETEXP-1249](https://connectustechnologies.atlassian.net/secure/RapidBoard.jspa?rapidView=3&modal=detail&selectedIssue=NETEXP-1249&assignee=5f91b571f162650070d4dc94)
Added additional props to AP details

feature/NETEXP-1249: Added Ap details props

---

src/containers/ProfileDetails/components/CaptivePortal/components/FormModal/tests/index.test.js
src/containers/ProfileDetails/components/CaptivePortal/index.js
src/containers/ProfileDetails/components/CaptivePortal/tests/index.test.js

- Fixed image uploading tests on Captive Portal Page
- Cleaned up test file to reduce duplicate code

hotfix/CaptivePortalTests: Fixed captive portal file uploading tests

---

src/containers/System/index.js

Option to show or hide system tabs

hotfix/Customers: Hide system tabs

---

src/containers/ProfileDetails/components/PasspointProfile/index.js
src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js
src/containers/ProfileDetails/constants/index.js
src/utils/profiles.js

JIRA: [WIFI-1722](https://telecominfraproject.atlassian.net/browse/WIFI-1722)
Removed required condition on HessId field. If not set manually by user, HessId is set to 00:00:00:00:00:00

bugfix/WIFI-1722: Removed required condition on HessId field

---

src/containers/ProfileDetails/components/Operator/index.js
src/containers/ProfileDetails/components/PasspointProfile/index.js
src/containers/ProfileDetails/components/ProviderId/components/OsuForm/index.js
src/containers/ProfileDetails/components/ProviderId/index.js
src/containers/ProfileDetails/components/Venue/index.js
src/containers/ProfileDetails/index.js

JIRA: [WIFI-1816](https://telecominfraproject.atlassian.net/browse/WIFI-1816)
Fixed all instances of saving bug on edit profile pages: Passpoint, Passpoint Id Provider, Passpoint Operator, Passpoint Venue

bugfix/WIFI-1816: Fixed saving bug on profile pages

---

src/containers/ProfileDetails/components/ProviderId/components/NaiRealm/constants/index.js
src/containers/ProfileDetails/components/ProviderId/components/NaiRealm/index.js

JIRA: [WIFI-1822](https://telecominfraproject.atlassian.net/browse/WIFI-1822)
Added the EAP methods: “EAP-AKA Prime Authentication" and “EAP-AKA" to ProviderId profile

bugfix/WIFI-1822: Added eap_aka methods to ProviderId profile

---

src/containers/AccessPointDetails/components/Firmware/index.js
src/containers/AccessPointDetails/components/General/index.js
src/containers/Accounts/components/FormModal/index.js
src/containers/AutoProvision/components/FormModal/index.js
src/containers/Dashboard/index.js
src/containers/Firmware/components/AssignmentModal/index.js
src/containers/Firmware/components/VersionModal/index.js
src/containers/Firmware/index.js
src/containers/Manufacturer/index.js
src/containers/ProfileDetails/components/CaptivePortal/components/FormModal/index.js
src/containers/ProfileDetails/components/RF/index.js

JIRA: [NETEXP-1287](https://connectustechnologies.atlassian.net/jira/software/c/projects/NETEXP/issues/NETEXP-1287?filter=myopenissues)
- Fixed all console log errors

bugfix/NETEXP-1287: Fix console log errors

---

src/containers/ProfileDetails/components/ProviderId/components/OsuForm/index.js
src/containers/ProfileDetails/components/ProviderId/index.js

JIRA: [WIFI-1815](https://telecominfraproject.atlassian.net/browse/WIFI-1815)
- Fixed bug on Passpoint Id Provider page that cleared some inputs when adding values from modals
- Fixed bug when deleting OSU elements from table

bugfix/WIFI-1815: Fixed Passpoint Id Provider page input bug

---

src/components/Navbar/components/Alarm/index.js
src/components/Navbar/components/Menu/index.js
src/components/Navbar/index.js

Fixed profiler re rendering issue with master layout. 
- Moved location state down to its nearest components 
- Created an alarm component because it needed the location state and the other components in that file didnt

htofix/Customers: fixed Master Layout Re-rendering

---

src/components/BulkEditAccessPoints/components/BulkEditAPTable/tests/index.test.js
src/containers/ProfileDetails/components/CaptivePortal/tests/index.test.js
src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js

Fixed file uploading tests for captive portal and passpoint pages, and bulk-edit-table test. 

hotfix/FixedBrokenTests: Fixed file uploading tests

---

src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js

JIRA: [WIFI-1911](https://telecominfraproject.atlassian.net/browse/WIFI-1911)
Added condition where users can only add 1 GRE Tunnel

bugfix/WIFI-1911: Added max GRE Tunnel condition

---

src/containers/AutoProvision/components/FormModal/index.js
src/containers/AutoProvision/index.js
src/containers/AutoProvision/tests/constants.js
src/containers/AutoProvision/tests/index.test.js

JIRA: [NETEXP-1399](https://connectustechnologies.atlassian.net/browse/NETEXP-1399)
Added Pagination for AP select in Auto-Provision page

bugfix/NETEXP-1399:  Added Pagination for AP select in Auto-Provision page

---

src/components/Navbar/index.module.scss

Fixed navbar z-index so that alerts could be properly shown

hotfix/NavbarStyle: Fixed navbar z-index

---

src/containers/Dashboard/components/LineChart/index.js
src/containers/Dashboard/index.js

JIRA: NOJIRA
Tue, Apr 13
- Allow user to set the timer length as a param into dashboard, default to 5m

hotfix/NOJIRA: Add prop to change dashboard timer amount

---

src/components/BulkEditAccessPoints/index.js
src/components/Navbar/components/Menu/index.js
src/components/Navbar/index.js
src/components/ToggleButton/index.js
src/containers/AccessPointDetails/index.js
src/containers/AppLayout/index.js
src/hooks/index.js
src/index.js

JIRA: NOJIRA
Thu, Apr 8
- Preserve query params when navigating to pages in the Network section of the app
Tue, Apr 13
- Use custom hook which has regular history object as well as functions to preserve query params

hotfix/NOJIRA: Created custom hook wrapping useHistory which allows user to preserve query param

---

src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/components/SSID/tests/index.test.js

JIRA: [WIFI-2016](https://telecominfraproject.atlassian.net/browse/WIFI-2016)
- Added input validation to SSID name field
- Removed periods from bandwidth error messages so they were consistent with page

bugfix/WIFI-2016: Added input validation to SSID name field

---

src/containers/ProfileDetails/components/AccessPoint/components/FormModal/index.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/Radius/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/components/constants.js
src/containers/ProfileDetails/constants/index.js

JIRA: [WIFI-1995](https://telecominfraproject.atlassian.net/browse/WIFI-1995)
Added NAS configuration fields for SSID profile. 
There were no fields for NAS client configuration, and the RADIUS fields were in the "Security and Encryption" card:
Added a separate card for all RADIUS related fields:

feature/WIFI-1995: NAS configuration fields for SSID profile

---

src/containers/Accounts/components/FormModal/index.js

JIRA: NOJIRA
bug:  when using Auth0 and editing email  an error occurs with an error response `Cannot update user that does not Exist`
Solution: disabled email changes when using Auth0

hotfix: If using Auth0 disable E-mail changes

---

src/containers/AccessPointDetails/index.js
src/containers/AccessPointDetails/index.module.scss

JIRA: [NO JIRA](LINK)
- added `extraIcon` prop to the ap details page

Feature: Added extraIcon prop on ap details

---

src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/General/tests/index.test.js
src/containers/AccessPointDetails/tests/constants.js

JIRA: [WIFI-2062](https://telecominfraproject.atlassian.net/browse/WIFI-2062)
Active and backup channel inputs were not in sync so error message would persist even when the error was corrected 
- Fixed this by making the manual active channel input dependent on the manual backup channel input and vice versa

bugfix/WIFI-2062: Added dependencies for AP Details channel inputs

---

src/components/Navbar/components/Menu/index.js
src/components/Navbar/components/Menu/index.module.scss

JIRA: [WIFI-2149](https://telecominfraproject.atlassian.net/browse/WIFI-2149)
Navbar sometimes showed ellipsis containing submenu items even though there was enough space to show all uncollapsed items. Fixed this issue to always show uncollapsed items when possible. 

bugfix/WIFI-2149: Fixed navbar resizing bug

---

src/components/DisabledText/index.js
src/components/DisabledText/index.module.scss
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/General/tests/index.test.js
src/containers/AccessPointDetails/tests/constants.js
src/containers/ProfileDetails/components/RF/index.js
src/containers/ProfileDetails/components/constants.js
src/containers/ProfileDetails/tests/constants.js
src/containers/ProfileDetails/tests/utils.js

NOJIRA: RF profile field changes

---

src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/PasspointProfile/index.js
src/containers/ProfileDetails/index.js
src/utils/profiles.js

JIRA: [WIFI-2015](https://telecominfraproject.atlassian.net/browse/WIFI-2015)
- Added ASRA field to passpoint profile
- Made error notification for no OSU SSID Profile more clear

bugfix/WIFI-2015: Added ASRA field to passpoint profile

---

src/containers/AccessPointDetails/components/Status/index.js
src/containers/AccessPointDetails/index.js

NO-JIRA
Cleanup Status Tab for AP Details Page

hotfix/ApDetailsStatusTab: Cleanup

---

src/components/DeviceHistory/index.js
src/containers/AccessPointDetails/components/OS/index.js

JIRA: NO-JIRA
Changed timestamps used in AP Details OS Stats graph & Client Device History graph from `createdTimestamp` to `sourceTimestampMs`

hotfix/ServiceMetricsTimestamps: Changed serviceMetrics timestamp

---

src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/Operator/index.js
src/containers/ProfileDetails/components/Operator/tests/index.test.js
src/containers/ProfileDetails/index.js
src/utils/profiles.js

JIRA: [WIFI-2606](https://telecominfraproject.atlassian.net/browse/WIFI-2606)
Fixed Operator profile "Domain Name List" field that was reset whenever an operator name was added
- Improved styling to make it consistent with other List inputs across the site rather than using commas as delimiters 
- Added logic to ensure Domain names are valid Domains and are unique 

bugfix/WIFI-2606: Fixed Operator profile "Domain Name List" field

---

src/containers/AccessPointDetails/components/OS/components/CombinedGraph/index.js
src/containers/Dashboard/components/LineChart/index.js
src/utils/formatFunctions.js

JIRA: NO-JIRA
- Fixed XAxis ticks so that the intervals are always consistent
- Fixed bug on dashboard graphs which would show irregular data when new data was fetched

hotfix/GraphXAxisTicks: Made xAxis intervals consistent on graphs

---

src/containers/AccessPointDetails/components/Status/index.js

JIRA: [WIFI-2636](https://telecominfraproject.atlassian.net/browse/WIFI-2636)
Added units to radio card

bugfix/WIFI-2636: Added units to radio card

---

src/containers/ProfileDetails/components/RF/index.js
src/containers/ProfileDetails/components/constants.js

JIRA: [WIFI-2596](https://telecominfraproject.atlassian.net/browse/WIFI-2596)
Added auto radio mode to RF profile and made it the default radioMode value

bugfix/WIFI-2596: Added auto radio mode to RF profile

---

src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/constants.js
src/containers/ProfileDetails/tests/utils.js
src/utils/profiles.js

JIRA: [WIFI-2637](https://telecominfraproject.atlassian.net/browse/WIFI-2637)
- Dynamic Discovery is triggered through the wildcard realm '*' where an additional option is shown and editable
- Made default value for `useMaxTxPower` "true"

bugfix/WIFI-2637: Added dynamicDiscovery to Radius Proxy Config

---

src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/index.js
src/utils/profiles.js

JIRA: [WIFI-2647](https://telecominfraproject.atlassian.net/browse/WIFI-2647)
Added support for Security and Encryption mode: `WPA3-Enterprise 192-Bit (SHA384-SuiteB)`

bugfix/WIFI-2647: Support WPA3-Enterprise 192-Bit (SHA384-SuiteB)

---

src/containers/ProfileDetails/components/AccessPoint/index.js

No-JIRA
Fixed console error related to incorrect initial state for `ntpServers`

hotfix/ApProfileNtpServers: Fixed console error

---

src/containers/AutoProvision/index.js
src/containers/Firmware/index.js
src/containers/Manufacturer/index.js
src/containers/System/index.js

NOJIRA
Mon Jun 28
- Refactor System to move Container to System instead of each individual components to make it more flexible.

NOJIRA: Refactor System

---

src/containers/AddProfile/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/index.js

- Scrolls to the first error on long profiles pages. 

WIFI/NOJIRA - Scroll form on error

---

src/components/Modal/index.js

- Pass a prop to the modal component to override a read only user to use the submit button in modal

WIFI/NOJIRA: Override read only submit button in modal

---

src/containers/AccessPointDetails/components/General/index.js

NOJIRA
Cleanup Rule Validation for AP Details Channel input

hotfix/ApDetailsChannelValidation: Cleanup rule validation

---

src/index.js
src/utils/sortRadioTypes.js

- Can export sortRadioTypes util function

NOJIRA: export sortRadioTypes

---

src/components/ContainedSelect/index.js

NO-JIRA
Fixed Z-Index for Contained Select Dropdown

hotfix/ContainedSelectZIndex: Fixed Z-index for Contained Select component

---

src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/index.module.scss

NO-JIRA
- Added null check to rf profile field 
- Changed routing behaviour on SSID summary table to make it consistent across site (previously it was only able to route when clicking the profile name, now it is routable on row click)

hotfix/ApDetailsRfProfileNullCheck: Added null check to RF profile field

---

src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/components/RF/index.js
src/containers/ProfileDetails/components/SSID/index.js
src/containers/ProfileDetails/components/constants.js
src/index.js

NO-JIRA
- Updated default values for SSID and RF profile
- Changed appliedRadios on SSID profile to only include 2.4GHz and 5GHz radios
- Fixed password error message

hotfix/UpdatedProfileDefaultValues: Updated Default Values for Profiles

---

src/containers/AccessPointDetails/components/Status/index.js
src/containers/AccessPointDetails/index.js

NO-JIRA
Added EIRP Tx Power to AP Details Status Tab

hotfix/EIRPTxPowerStatusTab: Added EIRP Tx Power to AP Details Status Tab

---

src/containers/ProfileDetails/index.js

- Changed profile details back button to use history to go back

NOJIRA: profile details history back btn

---

src/containers/AddProfile/index.js
src/containers/ProfileDetails/index.js

- Grammar fixes on rf profile error message

NOJIRA: RF Error Message

---

src/containers/ProfileDetails/components/SSID/index.js

NO-JIRA
Re-added (L) and (U) 5GHz radios to SSID profile

hotfix/SsidRadios: Re-added (L) and (U) 5GHz radios

---

src/components/LocationsTree/index.js
src/components/Skeleton/index.js
src/components/Skeleton/index.module.scss
src/containers/AccessPointDetails/components/Firmware/index.js
src/containers/AccessPointDetails/components/Firmware/tests/index.test.js
src/containers/AccessPointDetails/components/General/index.js
src/containers/AccessPointDetails/components/Location/index.js
src/containers/AccessPointDetails/components/OS/index.js
src/containers/AccessPointDetails/components/Status/index.js
src/containers/AccessPointDetails/index.js
src/containers/Accounts/index.js
src/containers/AppLayout/index.js
src/containers/AutoProvision/index.js
src/containers/AutoProvision/index.module.scss
src/containers/AutoProvision/tests/index.test.js
src/containers/BlockedList/index.js
src/containers/ClientDeviceDetails/components/DeviceDetailCard/index.js
src/containers/ClientDeviceDetails/components/DeviceStatsCard/index.js
src/containers/Dashboard/components/DeviceStatsCard/index.js
src/containers/Dashboard/components/LineChart/index.js
src/containers/Dashboard/components/PieChart/index.js
src/containers/Dashboard/index.js
src/containers/Dashboard/test/index.test.js
src/containers/Firmware/index.js
src/containers/Firmware/tests/index.test.js
src/containers/ProfileDetails/components/AccessPoint/index.js
src/containers/ProfileDetails/index.js
src/index.js

- Implemented skeleton loading throughout components

NOJIRA-SkeletonLoading

---

src/containers/Firmware/index.js

NOJIRA
Thun Jul 15
- Remove whitespace when creating/updating Firmware URL

bugfix/NOJIRA: Remove whitespace from FW URL

---

src/containers/BlockedList/index.js

- Fixed bug on delete blocked client modal

bugfix/NOJIRA: Delete Blocked Client Modal

---

src/containers/ProfileDetails/components/AccessPoint/index.js

NOJIRA
Thu Jul 15
- Add max SSID profiles per radio to 8
Tue Jul 21
- When 8 are selected on a radio the tag becomes red, and profiles with that radio are disabled in the Select

bugfix/NOJIRA: Add max SSID profiles

---

src/containers/Firmware/components/AssignmentModal/index.js
src/containers/Firmware/components/AssignmentModal/tests/index.test.js
src/containers/Firmware/components/VersionModal/index.js
src/containers/Firmware/components/VersionModal/tests/index.test.js
src/containers/Firmware/index.js

- Preserves firmware modal fields when closing 
- Resets on success

NOJIRA-FirmwareModals

---

src/containers/Dashboard/components/LineChart/index.js
src/containers/Dashboard/index.js
src/containers/Dashboard/test/index.test.js

NOJIRA
Wed Jul 21
- Restructure dashboard data for better compatibility with Recharts. 
- This gets rid of minor bugs
No visual change

Bugfix/NOJIRA: Restructure Dashboard Data

---

src/containers/BlockedList/index.js
src/containers/BlockedList/index.module.scss

- Added padding to blocked list on smaller devices

NOJIRA-BlockedList Responsiveness

---

src/components/LocationsTree/tests/utils.js
src/containers/AutoProvision/index.js
src/containers/AutoProvision/tests/constants.js
src/containers/AutoProvision/tests/index.test.js

NO-JIRA
-  Made auto-provision select hierarchical instead of flat-list 

hotfix/AutoProvisionLocation: Made auto-provision select hierarchical

---

src/components/Navbar/components/Menu/index.js
src/containers/Accounts/index.js
src/containers/Accounts/index.module.scss
src/containers/Dashboard/components/DeviceStatsCard/index.module.scss
src/containers/Dashboard/components/LineChart/index.js
src/containers/Dashboard/components/PieChart/index.js
src/containers/Dashboard/index.js
src/containers/Firmware/index.js
src/containers/Firmware/index.module.scss

- Added a few props to components that need style changes

feature/NOJIRA-Color Changes

---

src/index.js

JIRA: [NO-JIRA]
-added export for timer component

feature/NOJIRA: Added export for Timer

---

src/components/Navbar/components/Menu/index.js
src/components/Navbar/components/Menu/index.module.scss
src/components/Navbar/index.js
src/components/Navbar/index.module.scss
src/containers/AccessPointDetails/index.module.scss
src/containers/AppLayout/index.js
src/containers/AutoProvision/index.module.scss

JIRA: NOJIRA
- added css to inline menu to inherit color and background

bugfix/NOJIRA: Added CSS to inline menu

---

src/components/Navbar/components/Menu/index.js
src/components/Navbar/components/Menu/index.module.scss
src/components/Navbar/index.module.scss

JIRA: NOJIRA
- adjusted library css to accommodate antd library change
Update 2021-12-01
- removed surrounding spans preventing antd's default css from applying
- removed uneeded css

bugfix/NOJIRA: antd library change - light mode navbar css

---

src/components/GraphTooltips/LineGraphTooltip/index.js

JIRA: NOJIRA
-added extra tooltip data to line graph tool tips

feature/NOJIRA: Added extraTooltipData to tooltip

---

src/containers/Accounts/index.js
src/containers/Accounts/index.module.scss
src/containers/AutoProvision/index.js
src/containers/AutoProvision/index.module.scss
src/containers/BlockedList/index.js
src/containers/BlockedList/index.module.scss
src/containers/Firmware/index.js
src/containers/Firmware/index.module.scss

JIRA: NOJIRA
- removed all instances of `isLightIconProp`
- removed hard coloring on the clients blocked page

bugfix/NOJIRA: removed isLightIcon prop
