- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/index.js
JIRA: [TW-903](https://connectustechnologies.atlassian.net/browse/TW-903)
* Some AP uses 5GHz band instead of the explicit 5GHzU or 5GHzL band. Need to have an option to check on / off for the 5GHz option from the SSID profile*
*
*
> feature/TW-903- 5Ghz checkbox option

- src/components/LocationsTree/index.js
- src/containers/AccessPointDetails/components/Location/index.js
JIRA: [TW-916](https://connectustechnologies.atlassian.net/browse/TW-916)
*Can check only the Parent Tree Node (independent of the child nodes) to show APs of that immediate location. I.e. uncheck all children of node, but parent node will still be checked.*
*![Screen Shot 2020-07-23 at 12 45 53 PM](https://user-images.githubusercontent.com/64545886/88314410-e2ebc980-cce2-11ea-87d2-c0b5e09f930b.png)*
> Feature/TW-916: Parent locations of Location Tree need to be able to be checked

- src/containers/AccessPointDetails/components/OS/index.js
*Removed CAMI crashes alert on OS stats page*
*
*
> hotfix/CAMI - removed CAMI crashes alert

- src/containers/ProfileDetails/components/SSID/index.js
Fixed bug on SSID form that prevented the WPA Personal authentication mode from correctly rendering form items*
*
*
> hotfix/SSID Form

- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/components/Radius/components/RadiusZone/index.js
- src/containers/ProfileDetails/components/Radius/index.js
JIRA: [WIFI-777](https://telecominfraproject.atlassian.net/browse/WIFI-777)
- Added option to create a Radius profile under in addProfile 
- Added notifications to ensure details of the Radius form are filled properly
- Removed `Cannot update during an existing state transition (such as within `render`).` warning in RadiusZoneModal 
- Fixed newly found bug where subnet could not be added following a newly made Service Zone, now radius forms can be submitted smoothly
> hotfix/wifi-777: Added option to create a Radius Profile

- src/containers/ProfileDetails/components/Radius/index.js
- src/containers/ProfileDetails/components/index.module.scss
JIRA: [WIFI-770](https://telecominfraproject.atlassian.net/browse/WIFI-770)
Location of Service Zone and its Edit button & Remove button were visibly blocked by Radius Service table. Moved this information into it's down column beside table so they are no longer blocked
Additionally centered Collapse Title and Collapse arrow and modified the font's to match the other cards
> hotfix/WIFI-770: Moved Service Zone buttons to be visible

- src/containers/AccessPointDetails/components/General/index.js
JIRA: [WIFI-800](https://telecominfraproject.atlassian.net/browse/WIFI-800)
-Updated to the values & selection option for Channel Bandwidth to be is20MHz, is40MHz, and is80MHz
-Updated the values & selection option for Radio mode to be modeBGN, modeN, modeAC
- Remove dropdown option to select 80Mhz from 2.4Ghz Channel Bandwidth 
-Fixed save bug, the AP general page can now be updated and saved properly
> hotfix/WIFI-800: Updated values of channel bandwidth & Radio mode & removed 80Ghz option for 2.4GHz radio

- src/containers/Firmware/index.js
JIRA: [WIFI-844](https://telecominfraproject.atlassian.net/browse/WIFI-844)
- in the All Version table, disabled delete button of the version that is currently in use (in the Model Target Version table)
> hotfix/WIFI-844: Fixed disabling of the delete button of the select model in use

- src/containers/ProfileDetails/components/CaptivePortal/index.js
JIRA: [WIFI-811](https://telecominfraproject.atlassian.net/browse/WIFI-811)
- sets the url inputs as lower case when added & validates url input as lower case, to be no longer case sensitive
> hotfix/WIFI-811: Fixed captive_portal Profile's allow list to no longer be case sensitive

- src/containers/Manufacturer/index.js
JIRA: [WIFI-774](https://telecominfraproject.atlassian.net/browse/WIFI-774)
- only renders the Form.Item to set an Alias for OUI only when a correct OUI is searched, when `returnedOUI.oui` property is not null
- this PR is linked with the WIFI-774 PR in the library
> hotfix/WIFI-774: Fixed alias form.item to display only when correct OUI searched

- src/containers/ProfileDetails/index.js
- src/utils/profiles.js
JIRA: [WIFI-822](https://telecominfraproject.atlassian.net/browse/WIFI-822)
Issue
- radio button was not saving properly because `externalCaptivePortalURL` property is not being reset
- on save, the values of the current form are taken to be saved, if Access Point Hosted is selected `Form.Item` for  `externalCaptivePortalURL` does exist/appear in form thus cannot be reset
- CaptivePortal page is set up to check if `externalCaptivePortalURL` exist to select Externally Hosted on load
Solution
- on save check if the current form has value of `externalCaptivePortalURL` meaning Access Point Hosted is selected. then set the `externalCaptivePortalURL` in formattedData to be null
*Screenshots of what it will look like after …
> hotfix/WIFI-822: Fixed splash page Radio button save issue

- src/containers/AccessPointDetails/index.js
JIRA: [WIFI-904](https://telecominfraproject.atlassian.net/browse/WIFI-904)
- Made the `BACK` button a Header similar to the other tables
> hotfix/WIFI-904: Added padding to Back Button

- src/containers/ProfileDetails/components/CaptivePortal/index.js
- src/containers/ProfileDetails/components/index.module.scss
JIRA: [WIFI-820](https://telecominfraproject.atlassian.net/browse/WIFI-820)
- externalCaptivePortalURL was saving properly but not displaying in form w antd Form.Item `name` keyword due to being wrapped in a <div>
- used antd Input `defaultValue` keyword to display the saved url
-update name keyword is need for rules to be applied, added it back
> hotfix/WIFI-820: fixed external splash page URL save issue

- src/containers/Firmware/components/AssignmentModal/index.js
- src/containers/Firmware/index.js
JIRA: [WIFI-851](https://telecominfraproject.atlassian.net/browse/WIFI-851)
- added `prevFirmwareVersionRecordId` to be found and passed down to `onUpdateTrackAssignment` in the `createUpdateAssignment` function
- this PR is linked with [WIFI-851 of wlan-cloud-ui PR](https://github.com/Telecominfraproject/wlan-cloud-ui/pull/61)
> hotfix/WIFI-851: Added prevFirmwareVersionRecordId to Update Assignment

- src/containers/AccessPointDetails/components/General/index.js
JIRA: [WIFI-965](https://telecominfraproject.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=WIFI&modal=detail&selectedIssue=WIFI-965&assignee=5f93042addb0df006e8f3fed)
Put the radio types in sorted order in the advanced network settings.
> hotfix/WIFI-965: Sorted radio columns under advanced

- src/containers/Dashboard/components/LineChart/index.js
- src/containers/Dashboard/components/LineChart/index.module.scss
JIRA: [WIFI-789](https://telecominfraproject.atlassian.net/browse/WIFI-789)
- on dashboard when zooming in on line graphs surrounding graph text gets highlighted
- issue only occurs on safari browsers
solution
- make surrounding line graph text un-selectable specifically for safari browsers 
> hotfix/WIFI-789: fixed highlighting issue for safari browsers

- package-lock.json
- src/containers/AccessPointDetails/components/General/index.js
JIRA: [WIFI-1020](https://telecominfraproject.atlassian.net/secure/RapidBoard.jspa?rapidView=40&modal=detail&selectedIssue=WIFI-1020&assignee=5f93042addb0df006e8f3fed)
Set values of 'Ethernet MAC address' and 'Manufacturer' in Access Point details page under the Identity card. 
> hotfix/WIFI-1020: Set values to Ethernet Mac Addr and Manufacturer in AP Details page under Identity card

- package-lock.json
- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/components/Status/index.js
- src/utils/sortRadioTypes.js
- src/utils/sortRadios.js
JIRA: [WIFI-964](https://telecominfraproject.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=WIFI&modal=detail&selectedIssue=WIFI-964&assignee=5f93042addb0df006e8f3fed)
Fixed the alignment of Radio Columns on AP Status Page when values are missing. Used a grid layout instead of a flex layout. 
> hotfix/WIFI-964: Fixed alignment of Radio Columns on AP Status page

- src/containers/AccessPointDetails/components/Status/index.js
JIRA: [WIFI-1021](https://telecominfraproject.atlassian.net/jira/software/c/projects/WIFI/issues/WIFI-1021?jql=project%20%3D%20%22WIFI%22%20AND%20assignee%20IN%20%28currentUser%28%29%29%20ORDER%20BY%20created%20DESC)
Status tab in AP details page shows client devices. 
> hotfix/WIFI-1021: AP Details page Status tab shows client devices

- src/containers/Dashboard/components/LineChart/index.js
JIRA: [WIFI-1055](https://telecominfraproject.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=WIFI&modal=detail&selectedIssue=WIFI-1055&assignee=5f93042addb0df006e8f3fed)
added default values for the linecharts y-axis. 
> hotfix/WIFI-1055: added min values to linechart

- src/containers/AddProfile/index.js
JIRA: [NETEXP-649](https://connectustechnologies.atlassian.net/browse/NETEXP-649)
- disabled Bonjour Gateway option in Add Profile page
- temporary until this is implemented
> hotfix/NETEXP-649: disabled Bonjour Gateway option

- src/containers/ProfileDetails/components/AccessPoint/index.js
JIRA: [NETEXP-560](https://connectustechnologies.atlassian.net/browse/NETEXP-560)
- disabled LED Status check box and RTLS radio buttons
- temporary change
> hotfix/NETEXP-560: disabled LED Status and RTLS

- src/containers/Accounts/index.js
- src/containers/Accounts/tests/index.test.js
JIRA: [NETEXP-741](https://connectustechnologies.atlassian.net/browse/NETEXP-741)
- part of other PR on CMAP side [NETEXP-741](https://bitbucket.org/connectustechnologies/cmap-ui/pull-requests/28/bugfix-netexp-741-pass-down-getuser-data)
- stops rendering of delete button on Users page only for the current user.
> bugfix/NETEXP-741: fix being able to deleting current user

- src/containers/Dashboard/components/LineChart/index.js
- changed legend colour and legend hover colour to be consistent with rest of page
> hotfix/legendColor: Changed dashboard legend & hover colour

- src/containers/ProfileDetails/components/AccessPoint/index.js
JIRA: [NETEXP-841](https://connectustechnologies.atlassian.net/browse/NETEXP-841)
- When selecting a SSID profile the entire form is reset to what was initially, for `addProfile` previous values are the default values
SOLUTION:
- separated `childProfileIds` to it's own `form.setFieldsValue` to not impact rest of form when SSID's are added to the list
> fixed AP from resetting when SSID selected

- package-lock.json
- src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
- src/utils/bytes.js
JIRA: [NETEXP-930](https://connectustechnologies.atlassian.net/browse/NETEXP-930)
Fixed color inconsistencies on the highchart graph on the OS page. 
> bugfix/NETEXP-930: Color inconsistencies on OS highchart graph

- src/containers/ProfileDetails/components/RF/index.js
JIRA: [NETEXP-947](https://connectustechnologies.atlassian.net/browse/NETEXP-947)
Fixed RF Profile radio modes so that 2.4GHZ setting has all modes with b / g / n and 5GHz has all modes except ones with b / g.
Also fixed the Channel Bandwidth constraint on the 2.4GHz band. 
> bugfix/NETEXP-947: RF Profile Radio modes

- src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
- src/containers/AccessPointDetails/components/OS/components/SolidGauge/index.js
- src/containers/AccessPointDetails/components/OS/index.js
JIRA: [NETEXP-996](https://connectustechnologies.atlassian.net/browse/NETEXP-996)
-change "Current CPU" to "Current CPU Utilization"
-change "CPU Usage" to "CPU Utilization" 
-On "Current Free Memory" make below 25% yellow and below 10% red
-change Legend font color to #fff
> bugfix/NETEXP-996: OS stats labels and colors

- src/containers/ProfileDetails/components/SSID/index.js
JIRA: [NETEXP-999](https://connectustechnologies.atlassian.net/browse/NETEXP-999)
Changed order of security modes to:
wpa3-enterprise, 
wpa3Mixed-enterprise,
wpa3-personal,
wpa3mixed-personal, 
wpa2-enterprise, 
wpa2Mixed-enterprise, 
wpa2-personal, 
wpa2mixed-personal,
wpa-personal,
wep, open
> bugfix/NETEXP-999: fixed order of security and encryption modes

- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/components/constants.js
JIRA: [NETEXP-948](https://connectustechnologies.atlassian.net/browse/NETEXP-948)
- Fixed bug where security key would not appear for the security mode WPA2 Personal. 
- Changed initial security key default value from "w1r3l3ss-fr33d0m" to null 
> changed initial secureMode value

- src/containers/ProfileDetails/components/RF/index.js
JIRA: [NETEXP-947](https://connectustechnologies.atlassian.net/browse/NETEXP-947)
- Made 5GHz (L) and (U) the same as base 5GHz
- Changed label from X to AX and added it to the 2.4GHz band 
> NETEXP-947: Updated radio modes on RF profiles

- src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
- Y-Axis is now hidden when corresponding legend toggle is set
- Changed Legend name for CPU from `CPU Core [x]` to `CPU [x] Utilization`
> hotfix/OSGraphs: hide y-axis when legend is toggled off

- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/components/General/tests/index.test.js
- src/containers/ProfileDetails/components/RF/index.js
- src/containers/ProfileDetails/components/RF/tests/index.test.js
JIRA: [WIFI-1487](https://telecominfraproject.atlassian.net/browse/WIFI-1487)
Fixed input range for Client Disconnect Threshold  configuration fields.
General page: 
RF page: 
General page: 
RF page:
> bugfix/WIFI-1486: fixed input range for Client Disconnect Threshold

- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/CaptivePortal/index.js
- src/containers/ProfileDetails/components/PasspointProfile/index.js
- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/index.js
- src/utils/profiles.js
JIRA: [WIFI-1537](https://telecominfraproject.atlassian.net/browse/WIFI-1537)
In the Captive Portal Profile, the configured Radius server in Use was not displayed on refreshing the page.
-RADIUS profile id is now included as a child profile of the Captive portal
- Added an alert when RADIUS authentication is selected and user saves the form without selecting a RADIUS service
> bugfix/WIFI-1537: Radius authentication on Captive Portal Page

- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/components/SSID/tests/index.test.js
- src/containers/ProfileDetails/components/constants.js
- src/utils/profiles.js
JIRA: [NETEXP-1131](https://connectustechnologies.atlassian.net/browse/NETEXP-1131)
Data model changes for the AP profile and SSID profile
- Added dynamicVlan field to SSID profile
- Added default server to ntpServer value in AP profile 
- Fixed regex for IP address in AP profile 
- Fixed bug on SSID page where if the user toggled to NAT mode, the vlanID field would remain on the page 
> bugfix/NETEXP-1131: Data model Changes

- src/containers/AppLayout/index.js
- src/containers/AppLayout/index.module.scss
Having `overflow: auto` prevents `position: sticky` from working on all children and subchildren. This PR removes it.
> feature/NETEXP-1178: Remove overflow from AppLayout

- src/components/BulkEditAccessPoints/components/BulkEditAPTable/components/EditableCell/index.js
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/components/EditableCell/index.module.scss
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/components/EditableCell/tests/index.test.js
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/index.js
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/tests/index.test.js
- src/components/BulkEditAccessPoints/index.js
- src/components/BulkEditAccessPoints/tests/index.test.js
JIRA: [WIFI-1442](https://telecominfraproject.atlassian.net/browse/WIFI-1442)
- Save button is disabled by default and is only enabled when the user edits a row
- The saving functionality is changed so it only saves the row field on an edit, and not the entire row
- Added input validation to for each table field
> Bugfix/WIFI-1442: Bulk-Edit APs Page Fixes

- src/containers/AutoProvision/index.js
- src/containers/Firmware/index.js
- src/styles/index.scss
JIRA: [WIFI-1449](https://telecominfraproject.atlassian.net/browse/WIFI-1449)
Fixed global styles for tables so that long-text does not break table columns.
> hotfix/WIFI-1449: Long text can break table columns

- src/containers/ProfileDetails/components/SSID/index.js
- src/utils/profiles.js
JIRA: [WIFI-1621](https://telecominfraproject.atlassian.net/browse/WIFI-1621)
Fixed VLAN configuration settings on SSID page so Dynamic VLAN cannot be enabled with a Custom VLAN.
> bugfix/WIFI-1621: VLAN configuration fix for SSID profile

- src/components/Modal/index.js
- src/containers/AccessPointDetails/components/Firmware/tests/index.test.js
- src/containers/AccessPointDetails/tests/index.test.js
- src/containers/Accounts/index.js
- src/containers/Accounts/tests/index.test.js
- src/containers/AutoProvision/tests/index.test.js
- src/containers/BlockedList/tests/index.test.js
- src/containers/Firmware/tests/index.test.js
- src/containers/Profile/index.js
- src/containers/Profile/tests/index.test.js
- src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
- src/containers/ProfileDetails/components/CaptivePortal/components/Users/tests/index.test.js
- src/containers/ProfileDetails/components/CaptivePortal/tests/index.test.js
- src/containers/ProfileDetails/components/Operator/tests/index.test.js
- src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js
- src/containers/ProfileDetails/components/ProviderId/tests/index.test.js
- src/containers/ProfileDetails/components/Venue/tests/index.test.js
- src/containers/ProfileDetails/tests/index.test.js
Added `destroyOnClose` prop so that  child components and state logic are removed on modal close to improve performance. 
> hotfix/UnmountModalFix: Improve modal performance

- src/containers/Manufacturer/index.js
- src/containers/ProfileDetails/components/CaptivePortal/index.js
- src/containers/ProfileDetails/components/CaptivePortal/tests/index.test.js
- src/containers/ProfileDetails/components/PasspointProfile/index.js
- src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js
- src/containers/ProfileDetails/index.js
JIRA: [WIFI-824](https://telecominfraproject.atlassian.net/browse/WIFI-824)
Fixed issue where uploaded background/logo image on Captive Portal profile could not be previewed
- Added preview modal
- Changed file upload from a File object to a base64 string of the file
> bugfix/WIFI-824: File previewing fix for Captive-Portal profile

- src/containers/ProfileDetails/components/CaptivePortal/index.js
- src/containers/ProfileDetails/components/index.module.scss
- Fixed splash images style on Captive Portal Page so image would not break out of modal
- Fixed profile details scss style-sheet so items were not overly nested and were consistent with other style-sheets
> hotfix/CaptivePortalSplashImages: Fixed splash image styles

- src/containers/ProfileDetails/components/constants.js
JIRA: [WIFI-1487](https://telecominfraproject.atlassian.net/browse/WIFI-1847)
Changed default MIMO mode value from 2x2 to auto
> bugfix/WIFI-1487: Changed default MIMO mode value from 2x2 to auto

- src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
- src/containers/ClientDeviceDetails/components/DeviceDetailCard/index.js
- src/containers/ClientDeviceDetails/index.js
- src/utils/bytes.js
- src/utils/formatFunctions.js
JIRA: [NETEXP-1295](https://connectustechnologies.atlassian.net/browse/NETEXP-1295)
- Removed units from all y-axis labels and added them to respective y-axis values
> bugfix/NETEXP-1295: Fixed OS stats chart units

- src/containers/AccessPointDetails/components/Firmware/index.js
JIRA: [NETEXP-565](https://connectustechnologies.atlassian.net/jira/software/c/projects/NETEXP/issues/NETEXP-565?filter=myopenissues)
Disabled upgrade button when firmware upgrade is in progress
- status.upgradeState value is "undefined" when there is no upgrade in progress
- The reboot button is now disabled when the value is not "undefined"
Update Mar 19:
- Added more options that determine whether reboot button is disabled
Might have found a bug in the api:
When clicking upgrade firmware button on an ap, the response is successful:
`data :{
updateEquipmentFirmware: {
success: true,
__typename: "GenericResponse"
}
}`
But the `status.upgradeState` remains the same 'undefined' even when refetching the data.
> feature/NETEXP-565: Disable reboot btn when firmware upgrade in progress

- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/components/PasspointProfile/index.js
- src/containers/ProfileDetails/components/PasspointProfile/tests/index.test.js
- src/containers/ProfileDetails/index.js
- src/utils/profiles.js
JIRA: [NETEXP-1335](https://connectustechnologies.atlassian.net/browse/NETEXP-1335)
Fixed passpoint point profile creation and update:  Update all associated SSIDs profiles by putting the Passpoint profile ID in the `childrenIds` instead of passing in SSID profile as `childrenIds` of Passpoint profile itself
> bugfix/NETEXP-1335: Passpoint profile childProfileIds fix

- src/containers/ProfileDetails/components/SSID/index.js
JIRA: [WIFI-1895](https://telecominfraproject.atlassian.net/browse/WIFI-1895)
Fixed bug on SSID profile that allowed user to select captive profile in radius select.
Reason for bug: The field value for `radiusServiceId` was set using the profile at the 0th index of child profiles (`childProfiles.[0]`)
Solution: Find the radius profile if it exists instead of hardcoding the index
> bugfix/WIFI-1895: Fixed Radius select bug on SSID profile

- src/containers/AccessPointDetails/components/OS/components/HighChartGraph/index.js
- src/containers/AccessPointDetails/components/OS/index.js
JIRA: [NETEXP-1395](https://connectustechnologies.atlassian.net/browse/NETEXP-1395)
- made y-axis of OS stats graphs more consistent having min and max values
- Note in image free memory is not the actual max (510 Mb), graph shows 572 Mb due to axis being shared by 3 different properties.
- fixed label to show Mb instead of Kb, by formatting all values to Bytes for the Byte formatters
- related to cmap PR NETEXP-1395 https://bitbucket.org/connectustechnologies/cmap-ui/pull-requests/149
> Bugfix/NETEXP-1395: fixed freeMemory label + made OS stats y-axis more consistent

- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/components/SSID/tests/index.test.js
- src/containers/ProfileDetails/components/constants.js
JIRA: [WIFI-1992](https://telecominfraproject.atlassian.net/browse/WIFI-1992)
Allowed `radiusAcountingServiceInterval` to support valid input of 0, and made 0 the default value. 
Input used to support `null` input
> bugfix/WIFI-1992: Fixed radiusAcountingServiceInterval input

- package-lock.json
- src/components/LocationsTree/tests/index.test.js
- src/containers/AutoProvision/components/FormModal/tests/index.test.js
- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
- src/containers/ProfileDetails/components/constants.js
- src/containers/ProfileDetails/tests/constants.js
- src/containers/ProfileDetails/tests/utils.js
- src/utils/profiles.js
JIRA: [NETEXP-1461](https://connectustechnologies.atlassian.net/browse/NETEXP-1461)
- removed `equipmentDiscovery` from AP profile page and related such as testing files and utils validation
> bugfix/NETEXP-1461: Removed equipment discovery from Ap profiles

- package-lock.json
- src/containers/ProfileDetails/components/ProviderId/index.js
JIRA: [NETEXP-1450](https://connectustechnologies.atlassian.net/browse/NETEXP-1450)
- removed country and network from PLMN table
- these fields were already removed in the `plmnModal` 
> bugfix/NETEXP-1450: removed network & country from PLMN table

- src/containers/ProfileDetails/components/SSID/index.js
- src/utils/profiles.js
JIRA: [WIFI-2039](https://telecominfraproject.atlassian.net/browse/WIFI-2039)
- disabled Captive portal field when mode is NAT
- add condition to `formateSSID` so when the profile is updated to Mode NAT, child captive profile will be removed
> Bugfix/WIFI-2039: Disabled Captive Portal field when Mode is NAT

- src/components/ContainedSelect/index.js
- src/components/LocaleItem/index.js
- src/components/LocationsTree/components/AddApModal/index.js
- src/components/ModalSelect/index.js
- src/containers/Accounts/components/FormModal/index.js
- src/containers/AutoProvision/components/FormModal/index.js
- src/containers/Firmware/components/AssignmentModal/index.js
- src/containers/ProfileDetails/components/PasspointProfile/components/FormModal/index.js
- src/containers/ProfileDetails/components/ProviderId/components/NaiRealm/index.js
- src/index.js
JIRA: [NO JIRA](LINK)
- added reusable ContainedSelect component that uses `getPopupContainer` to ensure the select within a modal is the parent. By default the parent is the body
- used ContainedSelect in all instances where there was a select within a modal
Note this LocalItem was used in 3 other places, didn't add the images as they will all be the same
> hotfix: Added ModalSelect component

- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/index.js
- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/CaptivePortal/index.js
- src/containers/ProfileDetails/components/PasspointProfile/index.js
- src/containers/ProfileDetails/components/SSID/index.js
JIRA: NO_JIRA
- Fixed bug for all profile select drop-downs that did not reset profiles after a user made a search
- Fixed bug that showed search option for AP Details profile select when it was not needed 
> hotfix/ProfileSelectSearch: Fixed profile select search behaviour

- package-lock.json
- src/containers/ProfileDetails/components/SSID/index.js
- src/utils/profiles.js
JIRA: [WIFI-2039:](https://telecominfraproject.atlassian.net/browse/WIFI-2039)
- did the opposite before. 
- now disabled Captive Portal when mode is BRIDGE and enabled when mode is NAT
> Bugfix/WIFI-2039: Disable Captive Portal for BRIDGE mode

- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/index.js
JIRA: NO JIRA
bug: error messages related to child profiles were inconsistent for creating profiles compared to editing profiles. IE a required RADIUS profile when creating isn't required in editing or vice versa. 
solution: synced them up so that it should be the same now.
-also fixed the error notification for required OSU SSID in passpoint profiles due to `osuSsidProfileId` changing into an object
> hotfix: syncing up create & edit profiles error notifications

- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
- src/containers/ProfileDetails/components/CaptivePortal/index.js
- src/containers/ProfileDetails/components/index.module.scss
- src/containers/ProfileDetails/index.js
JIRA: [WIFI-2056](https://telecominfraproject.atlassian.net/browse/WIFI-2056)
-Added support for multiple NTP servers in AP profile
-Cleaned up AP profile by removing unused states
Multiple NTP Servers were supported but the UI wasn't helpful on what delimiters to use or the maximum length: 
List of NTP servers with input validation:
> bugfix/WIFI:2056: Added Multiple NTP server support

- package-lock.json
- src/containers/ProfileDetails/components/SSID/index.js
JIRA: [WIFI-2078](https://telecominfraproject.atlassian.net/browse/WIFI-2078)
bug: the NAS IP and NAS ID should only be available when the mode is Enterprise along with configured Radius
solution: made the Radius Card only available when the mode is one of Enterprise options 
> WIFI-2078: NAS ID and NAS IP should only appear for 802.1x Radius Auth

- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/constants/index.js
JIRA: [WIFI-1438](https://telecominfraproject.atlassian.net/browse/WIFI-1438)
bug: `802.11r/k/v` are boolean values and no longer support `auto` as an option
solution: removed auto as an option and as a default value, added the following Default values described in the JIRA ticket:
- 802.11r: Disabled
- 802.11k: Enabled
- 802.11v: Enabled
when mode is personal
when mode is enterprise
when mode is personal 
when mode is enterprise
> bugfix/WIFI-1438: removed auto as 80211x option

- src/containers/ProfileDetails/components/SSID/index.js
JIRA: [WIFI-2152](https://telecominfraproject.atlassian.net/browse/WIFI-2152)
- When switching to an enterprise security mode, the default value for 802.11r roaming is now `enabled` instead of `disabled`
- The comment regarding removing the "Auto" option was already done in the [SDK-profile cleanup](https://github.com/Telecominfraproject/wlan-cloud-ui-library/pull/232)
> bugfix/WIFI-2152: Changed 802.11r default roaming setting

- src/containers/ProfileDetails/components/ProviderId/index.js
- src/containers/ProfileDetails/components/ProviderId/tests/index.test.js
- src/utils/profiles.js
JIRA: [WIFI-2414](https://telecominfraproject.atlassian.net/browse/WIFI-2414)
- Added validation to roamingOI field so that each sub-element in the field must be 3-15 octets in length (octet is a pair of hex characters, e.g. A3), and no duplicate elements can be inputted
- Improved UI of field to make it a dynamic list instead of a comma separated input field
> bugfix/WIFI-2414: Added validation to roamingOI field

- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
- src/containers/ProfileDetails/index.js
JIRA: [WIFI-2437](https://telecominfraproject.atlassian.net/browse/WIFI-2437)
Cleanup RADIUS Proxy Configuration: 
- When RADSEC is enabled, hid the Accounting Shared Secret and Authentication Shared Secret Field
- Realm Domains must be unique across ALL RADIUS Proxy Configurations. Previously only Realm Domains within a configuration had the check
- Fixed display order of Proxies 
- Fixed RF profile only displaying ID in select field instead of name due to pagination
Hidden Shared Secret Fields: 
Realm Check:
> bugfix/WIFI-2437: Radius Proxy Configuration Cleanup

- src/containers/AccessPointDetails/components/Status/index.js
JIRA: [WIFI-2423](https://telecominfraproject.atlassian.net/browse/WIFI-2423)
Added RADIUS Proxy details to Access Point Details > Status Tab
- Added a new card called System which will show the RADIUS Proxy details
- Renamed old "Status" card to "Radio"
Connected Status:
Disconnected Status:
> feature/WIFI-2423: RADIUS Proxy info in Status tab

- src/containers/ProfileDetails/components/AccessPoint/index.js
JIRA: [WIFI-2522](https://telecominfraproject.atlassian.net/browse/WIFI-2522)
Fixed file upload `accept` condition for RADIUS Proxy certifications
- `accept="application/x-x509-ca-cert"` is not supported on Firefox or Safari
- Verified on Safari, Firefox and Chrome that using `accept=".pem"` works
> bugfix/WIFI-2522: Fixed RADIUS Proxy cert upload

- src/containers/AccessPointDetails/components/General/index.js
JIRA: [WIFI-2545](https://telecominfraproject.atlassian.net/browse/WIFI-2545)
Removed unsupported management rates for 5G radio in AP Details Inventory page
> bugfix/WIFI-2545: Removed unsupported rates for 5G radio

- src/containers/ProfileDetails/components/RF/index.js
JIRA: [WIFI-2640](https://telecominfraproject.atlassian.net/browse/WIFI-2640)
Changed `logical or` to `nullish-coalescing` on RFprofile:
-`logical or` deemed some allowed values like "0" as "falsy" and defaulted to the default RF profile value in `constants`
- Specifically for all the fields that allowed "0" as an allowed value
> bugfix/WIFI-2640: Changed "logical or" to "nullish-coalescing" on RFprofile

- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/components/index.module.scss
JIRA: [WIFI-2661)](https://telecominfraproject.atlassian.net/browse/WIFI-2661)
- Changed wording from "Captive Portal : Not Applicable" to "Captive Portal : Requires NAT Mode" 
- Made font size for disclaimer 12px to make it consistent with rest of form
> bugfix/WIFI-2661: Fixed phrasing for Network Mode disclaimer

- src/containers/AutoProvision/index.js
- src/containers/BlockedList/index.js
- src/containers/Firmware/index.js
- src/containers/Profile/index.js
- src/containers/ProfileDetails/components/CaptivePortal/components/Users/index.js
- src/containers/ProfileDetails/components/PasspointProfile/index.js
- src/containers/ProfileDetails/components/ProviderId/components/NaiRealm/index.js
NO-JIRA
- Any table that had a column with a preassigned width would not resize properly and would break out of the container
- Fixed all instances of this by adding `scroll={{ x: 'max-content' }}` as a prop
> hotfix/ProfilesTableStyling: Fixed table overflow bug

- src/containers/ProfileDetails/components/ProviderId/components/NaiRealm/index.js
- src/containers/ProfileDetails/constants/index.js
- src/utils/profiles.js
JIRA: [WIFI-2673](https://telecominfraproject.atlassian.net/browse/WIFI-2673)
- Fixed Select Dropdown that would not show options in Passpoint Provider Profile.  Fixed this by using the `ContainedSelect` component which uses the Antd prop `getPopupContainer` to fix the scrolling behaviour. 
- Correctly filled out the `eapMethods` attribute in the `naiRealmList` object
> bugfix/WIFI-2673: Fixed EAP method dropdown on Passpoint Provider profile

- src/containers/Dashboard/components/LineChart/index.js
NO-JIRA
Added null points to show disconnect between intervals longer than 10 minutes. Previously, the graph connected those points which was misleading. 
> hotfix/DashboardGraphs: Added null points to dashboard graphs

- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/SSID/tests/index.test.js
- src/utils/profiles.js
JIRA: [WIFI-2524](https://telecominfraproject.atlassian.net/browse/WIFI-2524)
- Removed required rule for Certificate Passphrase field
- Fixed bug where values for`sharedSecret` and `acctSharedSecret` were still passed in when `useRadSec` was enabled
> bugfix/WIFI-2524: Removed rule for Certificate Passphrase field

- src/components/ScrollToTop/index.js
- src/index.js
NO-JIRA 
Throughout the site, when there is a  long content page, it stays scrolled down when navigated to if the previous page was also scrolled. Fixed this by adding a `ScrollToTop` component that resets the scroll upon route change.
> hotfix/ScrollToTop: Added ScrollToTop  component

- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/utils/profiles.js
JIRA: [WIFI-2532](https://telecominfraproject.atlassian.net/browse/WIFI-2532)
Removed required rule for `Client Certification` and `Client Key` files. Only the `CA Cert` file is now required when `RADSEC` is enabled
> bugfix/WIFI-2532: Removed required rule for proxy certs files

- src/containers/Dashboard/components/LineChart/index.js
- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/components/constants.js
JIRA: [WIFI-2031](https://telecominfraproject.atlassian.net/browse/WIFI-2031)
Added Proxy-ARP field to SSID profile - field is disabled by default. 
> bugfix/WIFI-2031: Proxy-ARP field for SSID profile

- src/containers/AccessPointDetails/components/General/constants.js
- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/components/General/tests/index.test.js
JIRA: [WIFI-2727](https://telecominfraproject.atlassian.net/browse/WIFI-2727)
Added validation for Radio Channels:
For both 2.4GHz and 5Ghz: 
-Added list of allowed channels which will be used to validate if input is valid 
For 5Ghz: 
- Added check so that DFS channel should not be allowed as Backup Channel for 5GHz Radio
- Added check to dynamically update allowed channels based on rf-profile bandwidth 
> bugfix/WIFI-2727: Validation for radio channels

- src/containers/ProfileDetails/components/SSID/index.js
- src/containers/ProfileDetails/constants/index.js
- src/utils/sortRadioTypes.js
NO-JIRA
Changed Sort Order on SSID page from "2.4GHz,  5GHz (L), 5GHz (U), 5GHz" to "2.4GHz, 5GHz, 5GHz L, 5GHz U"
Changed 
> hotfix/RadioSortOrder: Changed radio sort order

- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/index.js
JIRA: [WIFI-2854](https://telecominfraproject.atlassian.net/browse/WIFI-2854)
Made RF/SSID profiles selections required on AP profile. Previously, an AP profile could be created and updated without them.
> bugfix/WIFI:2854: Made RF/SSID profiles selections required on AP profile

- src/containers/ProfileDetails/components/CaptivePortal/index.js
JIRA: [WIFI-2855(https://telecominfraproject.atlassian.net/browse/WIFI-2855)
- Captive Portal BE does not support multi-line input for "User Acceptance Policy Text" & "Login Success Text": Changed field from "TextArea" to regular "Input"
- Removed unused styles
> bugfix/WIFI-2855: Changed Splash Page body content input fields

- src/containers/ClientDeviceDetails/index.js
JIRA: [WIFI-2826](https://telecominfraproject.atlassian.net/browse/WIFI-2826)
Mon Jun 28
Use the latest metric to show the Client Device stats instead of metricDetails which has been deprecated.
- Throughput => bytes/periodLengthSec
- packets => frames
- kbps => averageRate
> bugfix/WIFI-2826: Use Latest Metric for stats

- src/containers/ProfileDetails/components/AccessPoint/index.js
NO-JIRA
- Fixed value for "Warning (WARNING)" option in Syslog Log field
- Added "addOnBefore" text for fields to make them consistent across profile 
> hotfix/ApProfileSyslogField: Fixed syslog warning option value

- src/containers/ProfileDetails/components/SSID/index.js
NO-JIRA
- Changed `min` value on RADIUS Accounting Interval input field from "60" to "0" to fix bug that prevented user from saving profile when value was 0 
> hotfix/SsidRadiusAcctInterval: Fixed RADIUS Accounting Interval input field

- src/components/DisabledText/index.js
- src/containers/AccessPointDetails/components/General/constants.js
- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/components/General/tests/index.test.js
- src/containers/AccessPointDetails/components/Status/index.js
- src/containers/AccessPointDetails/index.module.scss
JIRA: [WIFI-2962](https://telecominfraproject.atlassian.net/browse/WIFI-2962)
Quality of Life improvements to AP Details Page: 
- General and Status tab now show channel bandwidth from associated RF-Profile
- Clicking on the name of the RF-Profile or SSID profile on the General page will route user to the specific profile 
> bugfix/WIFI-2962: Added channel bandwidth to AP details page

- src/components/Button/index.module.scss
- src/containers/AccessPointDetails/components/Firmware/index.js
- src/containers/AccessPointDetails/components/Firmware/tests/index.test.js
- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/components/Location/index.js
- src/containers/AccessPointDetails/components/Status/index.js
- src/containers/AccessPointDetails/index.js
- src/containers/AccessPointDetails/index.module.scss
- src/containers/AccessPointDetails/tests/constants.js
- src/containers/AccessPointDetails/tests/index.test.js
- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/index.js
- src/containers/ProfileDetails/tests/index.test.js
JIRA: [WIFI-2413](https://telecominfraproject.atlassian.net/browse/WIFI-2413)
Calling the update equipment API in quick succession with the same profile, causes the cloud to push the profiles twice and results in duplicate VifC ssid and VifS failure. To fix, made the saved button disabled when form is untouched. 
- Fixed null check on `renderBandwidthLabels` function
- Improved phrasing on "Leave Page" modals
> bugfix/WIFI-2419: Disabled Save Button on Untouched AP Details page

- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AccessPointDetails/components/General/tests/index.test.js
- src/containers/ProfileDetails/components/RF/index.js
- src/containers/ProfileDetails/components/RF/tests/index.test.js
- src/containers/ProfileDetails/tests/constants.js
NO-JIRA
Changed input field ranges on RF profile:
- Probe Response Threshold: -100 - 100 dm →  -100 - -40 dm
- Rx Cell Size: -100 - 100 dm →  -100 - 0 dm
- Auto Cell Size Selection:  Now shows 'N/A' when radio-mode 'modeA' is selected
- Removed 'modeB' option from 2.4Ghz Radio Mode
- Active Scan Setting → Scan Frequency:  0 - 100 seconds →   10 - 100
- Active Scan Setting → Scan Duration:  0 - 100 milliseconds →   50 - 100
> hotfix/RfProfileCleanup : Cleanup input ranges on Rf profile

- src/containers/AccessPointDetails/components/Firmware/index.js
NOJIRA
Thu Jul 15
- There is a case where the AP gets stuck in the `apply_failed` state. In this case, we want the user to be able to reattempt the firmware upgrade manually.
- Move the current upgrade status stag to the Upgrade card.
- Don't show current firmware in the target version list.
- Will be affected until WIFI-2650 is fixed where `apply_failed` is set erroneously but not breaking issue
> Bugfix/NOJIRA: Upgrade Firmware

- src/utils/profiles.js
NO-JIRA
Following fields in provider ID profile are required by the AP for the Hotspot20_OSU_Providers table in order to come up properly:
- osuNaiStandalone
- osuNaiShared
> hotfix/PasspointProviderIdNaiFields: Empty strings instead of null for Nai fields

- src/containers/ProfileDetails/components/SSID/index.js
NO-JIRA
Hide Proxy-ARP field on SSID profile as AP needs to have proxy ARP enabled for WIFI 6 to work properly. This field will always be internally set to enabled. 
> hotfix/SsidProxyArp: Hide Proxy-ARP field

- src/containers/AccessPointDetails/components/General/constants.js
- src/containers/AccessPointDetails/components/General/index.js
NO-JIRA
Bug: RF profile is displayed as NA and Summary table is empty on page load, even though a valid RF profile is configured.
- Fixed selectedProfiles state due to new skeleton loading
- Fixed channel input on selectedProfile change (previously it would not update field value)
- Removed channel bandwidth validation on Channel input 
> hotfix/ApDetailsSelectedProfiles: Fixed selectedProfiles state

- src/containers/AccessPointDetails/components/General/index.js
NOJIRA
Thu Jul 22
- Perimeter Detection field has no placeholder on AP. This field can be removed from the UI for now
> Bugfix/NOJIRA: remove permieter detection

- src/containers/ClientDeviceDetails/index.js
- src/utils/formatFunctions.js
JIRA: [WIFI-2842](https://telecominfraproject.atlassian.net/browse/WIFI-2842)
- Deleted IP Lease Start Time Label
- Added null checks to prevent `NaN` labels
> bugfix/WIFI-2842: Deleted IP Lease Start Time Label

- src/components/BulkEditAccessPoints/components/BulkEditAPTable/components/EditableCell/index.js
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/components/EditableCell/tests/index.test.js
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/index.js
- src/components/BulkEditAccessPoints/components/BulkEditAPTable/tests/index.test.js
- src/components/BulkEditAccessPoints/index.js
- src/components/BulkEditAccessPoints/index.module.scss
- src/components/BulkEditAccessPoints/tests/index.test.js
NO-JIRA
- Added allowedChannels validator to ensure that each channel input for radio is valid
- Added radio column to improve user-experience
- Fixed input ranges for cell-sizing fields to match RF-profile: 
```
- Rx Cell Size: -100 - 100 --> -100 - 0
- Probe Response Threshold: -100 - 100 --> -100 - -40
- Client Disconnect Threshold: 100 - 0 --> -100 - 0
```
- Added skeleton loading instead of spinner
> hotfix/BulkEditAllowedChannels: Added allowed channels to bulk-edit table

- src/containers/AccessPointDetails/components/General/index.js
- src/containers/AddProfile/index.js
- src/containers/ProfileDetails/components/RF/index.js
- src/containers/ProfileDetails/components/RF/tests/index.test.js
- src/containers/ProfileDetails/constants/index.js
NO-JIRA
- Added channel bandwidth validation in the RF profile to match the following configuration for 5GHz radios. Previously, all 5 modes supported all 4 channel bandwidths.
- Updated configuration map:
`auto: ['20MHz', '40MHz', '80MHz', '160MHz']`
` modeN: ['20MHz', 'is40MHz']`
` modeA: ['20MHz']`
`modeAC: ['20MHz', '40MHz', '80MHz', '160MHz']`
`modeAX: ['20MHz', '40MHz', '80MHz', '160MHz']`
- Fixed bug where Cell Sizing inputs would not show up for "Add Profile"
- Changed error messages to human readable radios
Mode N: 
Mode A:
> hotfix/RfProfileAllowedChannels: Added Channel Bandwidth Validation for RF profile

- src/containers/AccessPointDetails/components/Firmware/index.js
NOJIRA
Wed Aug 4
- Tweak percentages so that the upgrade progress bar is more smooth since it only really is in three stages during the upgrade. Now user will see 20%, 40%, and 80% before completing
> NOJIRA: Fixed Upgrade progress bar

- .github/workflows/bump-version.yml
- Auto updates the package version on push
- used a package that bypasses protected repos
**For this to work**:
1. On Github click the icon in top right and go to `settings` 
2. On the left side click `developer settings` then >  `Personal Access Tokens`
3. Click Generate new token. I named it `PUSH_TO_PROTECTED_BRANCH` 
4. Give it these scopes: 
5. Click Update Token and copy the key 
5. back into the Repo now and go to Settings > Secrets > New repository secret
6. name: `PUSH_TO_PROTECTED_BRANCH`, value: `<> the token key that was generated  </>`
> bugfix/NOJIRA-AutoUpdatePackage 

- src/containers/AccessPointDetails/components/Firmware/index.js
NO-JIRA
Disabled  'switch to inactive bank' button on AP Details Firmware page as it is currently unsupported
> hotfix/ApDetailsFirmware: Disable 'switch to inactive bank' button

- src/containers/ProfileDetails/components/AccessPoint/index.js
- src/containers/ProfileDetails/components/AccessPoint/tests/index.test.js
NO-JIRA
Removed unsupported input -  `Management VLAN `from AP Profile
> hotfix/ApProfileVLAN: Removed Management VLAN input from AP profile

- src/containers/Dashboard/components/PieChart/index.js
NOJIRA
- Prevent pie chart labels from overlapping by only showing labels if they slice is more than 5%
> NOJIRA: Pie Chart Overlap Fix
